spring.application.name=hortalapp-backend


# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/hortalapp_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8080

jwt.secret=hortalapp_clave_secreta_super_segura_2024
jwt.expiration=86400000